# Generated by Django 5.2.6 on 2025-10-09 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('key_responsibilities', models.TextField(blank=True, help_text='Comma-separated list of key responsibilities')),
                ('qualifications', models.TextField(blank=True, help_text='Comma-separated list of required qualifications')),
                ('compensation', models.TextField(blank=True, help_text='e.g., Salary range, benefits')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('job_type', models.CharField(blank=True, help_text='e.g., Engineering, Research, Marketing', max_length=100)),
                ('employment_type', models.CharField(blank=True, help_text='e.g., Remote, Urgent', max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.CharField(blank=True, max_length=255)),
                ('job_tags', models.TextField(blank=True, help_text='Comma-separated list of job tags (e.g., Python, ML, Data Science)')),
                ('accepting', models.BooleanField(default=True, help_text='Is this position currently accepting applications?')),
            ],
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, help_text='e.g., Partnership, Product Launch, Event', max_length=100)),
                ('disclaimer', models.TextField(blank=True, help_text='Optional legal disclaimer or note')),
                ('content', models.TextField(blank=True)),
                ('meta_tag1', models.CharField(blank=True, help_text='SEO meta tag 1', max_length=100)),
                ('meta_tag2', models.CharField(blank=True, help_text='SEO meta tag 2', max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='careers/resumes/')),
                ('cover_letter', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_applications', to=settings.AUTH_USER_MODEL)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.career')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Short biography or description')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('linkedin', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Profile creation datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Profile last updated datetime')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
