# Generated by Django 5.2.6 on 2025-10-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerapplication',
            old_name='cover_letter',
            new_name='links',
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
