# Generated by Django 5.2.6 on 2025-11-13 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pressrelease',
            old_name='published_at',
            new_name='created_at',
        ),
    ]
