# Generated by Django 5.2.6 on 2025-11-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_posted_at_career_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='career',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
