# Generated by Django 5.2.6 on 2025-10-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cover_letter_careerapplication_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
    ]
