# Generated by Django 5.2.6 on 2025-10-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_bio_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressrelease',
            name='meta_tag1',
        ),
        migrations.RemoveField(
            model_name='pressrelease',
            name='meta_tag2',
        ),
    ]
