# Generated by Django 5.2.6 on 2025-10-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_pressrelease_meta_tag1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressrelease',
            name='meta_tags',
            field=models.TextField(blank=True, help_text='Comma-separated meta tags for SEO'),
        ),
    ]
