# Generated by Django 5.0 on 2024-05-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('question_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='media/images/answers/')),
                ('answer_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('minutecount', models.IntegerField(default=0)),
                ('blog_category', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='media/images/blogs/banners/')),
                ('main_body', models.TextField(blank=True, null=True)),
                ('second_body', models.BooleanField(default=False)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='media/images/blogs/images')),
                ('second_text', models.TextField(blank=True, null=True)),
                ('third_body', models.BooleanField(default=False)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='media/images/blogs/images')),
                ('third_text', models.TextField(blank=True, null=True)),
                ('fourth_body', models.BooleanField(default=False)),
                ('fourth_image', models.ImageField(blank=True, null=True, upload_to='media/images/blogs/images')),
                ('fourth_text', models.TextField(blank=True, null=True)),
                ('fifth_body', models.BooleanField(default=False)),
                ('fifth_image', models.ImageField(blank=True, null=True, upload_to='media/images/blogs/images')),
                ('fifth_text', models.TextField(blank=True, null=True)),
                ('sixth_body', models.BooleanField(default=False)),
                ('sixth_image', models.ImageField(blank=True, null=True, upload_to='media/images/blogs/images')),
                ('sixth_text', models.TextField(blank=True, null=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('comment_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('blog_id', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='media/images/comments/')),
                ('comment_body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('book_category', models.CharField(blank=True, max_length=100, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='media/images/books/')),
                ('book_title', models.CharField(blank=True, max_length=100, null=True)),
                ('book_writer', models.CharField(blank=True, max_length=100, null=True)),
                ('book_size', models.IntegerField(default=0)),
                ('book_file', models.FileField(blank=True, null=True, upload_to='media/files/books/')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sem_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='media/images/members/')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('ru', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('question_title', models.CharField(blank=True, max_length=200, null=True)),
                ('question_description', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('total_answer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sem_id', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/files/resources/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('sem_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/teachers/')),
                ('expertise', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerReply',
            fields=[
                ('reply_answer_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='media/images/answers/')),
                ('reply_answer_description', models.TextField(blank=True, null=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mse.answer')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('reply_comment_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('userimage', models.ImageField(blank=True, null=True, upload_to='media/images/comments/')),
                ('reply_comment_body', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mse.blogcomment')),
            ],
        ),
    ]
